#This script will generate a prediction algorithm for human movements based on the data generated by
#a magnetic sensor on each arm, each leg and the torso of the test person

if(!require(tidyverse)) install.packages("tidyverse", repos = "http://cran.us.r-project.org")
if(!require(caret)) install.packages("caret", repos = "http://cran.us.r-project.org")
if(!require(data.table)) install.packages("data.table", repos = "http://cran.us.r-project.org")
if(!require(scales)) install.packages("scales", repos = "http://cran.us.r-project.org")
if(!require(scales)) install.packages("tinytex", repos = "http://cran.us.r-project.org")

########################### Make data ready to use ############################

#----------------------------- Establish the basic tables out ot the raw data ---

#Define column names (legend: T=torso, RA=right arm, LA=left arm, RL=right leg, LL=Left leg / x,y,z = axis of direction /
#acc=accelerometer, gyro=gyroscope, mag=magnetometer)
ColNames <- c("T_xacc", "T_yacc", "T_zacc", "T_xgyro", "T_ygyro", "T_zgyro", "T_xmag", "T_ymag", "T_zmag",
              "RA_xacc", "RA_yacc", "RA_zacc", "RA_xgyro", "RA_ygyro", "RA_zgyro", "RA_xmag", "RA_ymag", "RA_zmag",
              "LA_xacc", "LA_yacc", "LA_zacc", "LA_xgyro", "LA_ygyro", "LA_zgyro", "LA_xmag", "LA_ymag", "LA_zmag",
              "RL_xacc", "RL_yacc", "RL_zacc", "RL_xgyro", "RL_ygyro", "RL_zgyro", "RL_xmag", "RL_ymag", "RL_zmag",
              "LL_xacc", "LL_yacc", "LL_zacc", "LL_xgyro", "LL_ygyro", "LL_zgyro", "LL_xmag", "LL_ymag", "LL_zmag")

#um schneller rechnen zu können anziehen des Files aus lokalem Verzeichnis
#temp <- "C:/Users/fure/OneDrive/Projects/R/TempRohDaten/data/a01/p1/s01.txt"
#a1 <- read_delim(temp, delim = ",", col_names = ColNames)

#for(y in personNumber){
#  for(x in fileNames){
#    file <- paste0("C:/Users/fure/OneDrive/Projects/R/TempRohDaten/data/a01/p",y,paste0("/s",x,".txt"))
#    a1 <- cbind(a1, read_delim(file, delim = ",", col_names = ColNames))
#    a1
#  }
#}

#Download the zip File with the raw data
dl <- tempfile()
download.file("https://publicdatarfu.blob.core.windows.net/publicdatarfucontainer/data.zip", dl)

#Generate the basic table for activity nb 1 just with one file:
temp <- unzip(dl, "data/a01/p1/s01.txt")
a1 <- read_delim(temp, delim = ",", col_names = ColNames)

#Build file a1 --> all measurements from all person for activity nb 1:
fileNames <- sprintf("%02d",seq(1:60))
personNumber <- seq(1:8)

for(y in personNumber){
  for(x in fileNames){
    file <- unzip(dl,paste0("data/a01/p",y,paste0("/s",x,".txt")))
    a1 <- cbind(a1, read_delim(file, delim = ",", col_names = ColNames))
    a1
  }
}
identical(a1[,1:45], a1[,46:90]) #first file is a double count because of the choicen approach
a1[1:45] <- list(NULL) #delete the frist file (first 45 columns)
#a1
dim(a1)